### ISSUE TITLE
The calculate() function should not be doing a database calculation. Just a standard calc

### ISSUE THREAD

**Issue by pjayathissa** [pjayathissa/algorithm-audit#4]
https://github.com/pjayathissa/algorithm-audit/blob/b61e3368f024d27c2f9e35baa2ad2d7c27734ca8/calculators/RenalTransplant/calculator_renal_transplant.py#L165

And it should have all the arguments required to do a single calculation

```python
def calculate(age, albumin, dateToFirstRTT ....)

I want to keep databasing (pandas, numpy etc) out of the calculate script to keep it clean

**Comment by uditsharma16** [comment]
Done.

**Comment by pjayathissa** [comment]
Nice, just bring the `calculate()` function to the top of the script

**Comment by uditsharma16** [comment]
Done.
