### ISSUE TITLE
Can we bring the test data to a csv file

### ISSUE THREAD

**Issue by pjayathissa** [pjayathissa/algorithm-audit#5]
https://github.com/pjayathissa/algorithm-audit/blob/b61e3368f024d27c2f9e35baa2ad2d7c27734ca8/calculators/RenalTransplant/test_renal_transplant.py#L9

I really like how you are testing each function individually. It's great. I think if we can bring this test data to a csv, it can be used for testing each function as you have done, and also test the whole algorithm on all the data

**Comment by uditsharma16** [comment]
Completed.
