### ISSUE TITLE
May be too difficult for future development. How could this be simplified?

### ISSUE THREAD

**Issue by pjayathissa** [pjayathissa/algorithm-audit#6]
https://github.com/pjayathissa/algorithm-audit/blob/b61e3368f024d27c2f9e35baa2ad2d7c27734ca8/calculators/RenalTransplant/validation_renal_transplant.py#L18

As we discussed, we need this code to be as simple as possible. The detail you have created here is amazing. But once you leave, I don't think we have the capacity to maintain such high standards. The DHB has really limited dev capacity so we need to keep this in mind. 

Would you be able to explore the simplest way of writing the validation script. And then in the future we can start expanding. It could even just be as simple as comparing the overall results, and printing the datapoints where there was a mismatch as a csv.

**Comment by uditsharma16** [comment]
Please check I have performed some simplifications

**Comment by pjayathissa** [comment]
I like it, good work :)
